#!/usr/bin/env python3

# ========================= #
# PACKAGE RELEASE           #
# ========================= #

import os, sys
import shutil
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(REPO_ROOT)

def run(command):
    return check_call(command, shell=True)

try:
    # Has the form "major.minor"
    python_version = os.environ['PYTHON_VERSION']
except KeyError:
    python_version = '.'.join([str(i) for i in sys.version_info[:2]])

if os.path.isdir('dist') and os.listdir('dist'):
    shutil.rmtree('dist')
run('python3 setup.py sdist')