#!/usr/bin/env python3

import os
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(os.path.join(REPO_ROOT, 'test'))

def run(command):
    return check_call(command, shell=True)

run('python3 -m unittest discover -v')